config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {omniauth_callbacks: 'users/omniauth_callbacks'}
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :products
  resources :orders
  resources :carts
  get '/profile' => 'users#show'
  get '/change_myinfo' => 'users#edit'
  patch '/change_myinfo' => 'users#update'
  get '/' => 'users#index'
  get '/error' => 'problems#index'
  get '/accept/:id' => 'problems#show'
  get '/decline/:id' => 'problems#edit'
  get '/complete/:id' => 'problems#new'
end

app/models/product.rb
class Product < ApplicationRecord
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
    before_action :authenticate_user!
    def index 
        
        if current_user.long==""
            redirect_to change_myinfo_path
        else
            authorize! :index, Product, message: "Non sei autorizzato"
            @all=Product.all
        end
    end
    def def new
        
        if current_user.long==""
            authorize! :create, Product, message: "Non sei autorizzato"
            redirect_to change_myinfo_path
        else
        end
    end
    def create
        
        if current_user.long==""
            redirect_to change_myinfo_path
        else
            authorize! :create, Product, message: "Non sei autorizzato"
            p=params.permit(:imagePath, :title, :description, :category)
            Product.create!(p)
            redirect_to products_path
        end
    end

    def edit
        
        if current_user.long==""
            redirect_to change_myinfo_path
        else
            authorize! :update, Product, message: "Non sei autorizzato"
            id=params[:id]
            if Product.exists?(id)
                @product=Product.find(id)
            else
                render html: "Il Prodotto non esiste"
            end
        end
    end
    def update
        
        if current_user.long==""
            redirect_to change_myinfo_path
        else
            authorize! :update, Product, message: "Non sei autorizzato"
            Product.find(params[:id]).update(params.permit(:imagePath, :title, :description, :category))
            redirect_to products_path
        end
    end
    def destroy
        
        if current_user.long==""
            redirect_to change_myinfo_path
        else
            authorize! :destroy, Product, message: "Non sei autorizzato"
            id=params[:id]
            if Product.exists?(id)
                @product=Product.find(id)
                @product.destroy
                redirect_to products_path
            else
                render html: "Il Prodotto non esiste"
            end
        end
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product_form.html.erb
<% if product != nil %>
<div class="form-group">
    <%= form.label "Immagine"%><br />
    <%= form.text_field :imagePath, required: true , value: product.imagePath, :class=>"form-control" %><br>
</div>
<div class="form-group">
    <%= form.label "Titolo"%><br />
    <%= form.text_field :title, required: true , value: product.title, :class=>"form-control"  %><br>
</div>
<div class="form-group">
    <%= form.label "Descrizione"%><br />
    <%= form.text_area :description, required: true  , value: product.description, :class=>"form-control" %><br>
</div>
<div class="form-group">
    <%= form.label "Categoria"%><br />
    <%= form.text_field :category, required: true  , value: product.category, :class=>"form-control" %><br>
</div>
<% else %> 
<div class="form-group">
    <%= form.label "Immagine"%><br />
    <%= form.text_field :imagePath, required: true, :class=>"form-control"  %><br>
</div>
<div class="form-group">
    <%= form.label "Titolo"%><br />
    <%= form.text_field :title, required: true, :class=>"form-control"  %><br>
</div>
<div class="form-group">
    <%= form.label "Descrizione"%><br />
    <%= form.text_area :description, required: true, :class=>"form-control"  %><br>
</div>
<div class="form-group">
    <%= form.label "Categoria"%><br />
    <%= form.text_field :category, required: true, :class=>"form-control"  %><br>
</div>
<% end %>
 

app/views/products/edit.html.erb
<div style="height: 80vh; margin-top:2cm;">
<div class="row mx-auto" style="margin-bottom: 0.5cm;">
    <div class="col-md-4 col-md-offset-4 mx-auto">
        <h1 class="text-center" style="font-size: 30px;">Modifica Prodotto <%=@product.title%>
        </h1>
      <%= form_with url: product_path(@product),class: "formABC" ,method: :put do |form| %>
        <%= render partial: "product_form", locals: {form: form, product: @product} %>
        
        <input type="submit" class="btn btn-success">

      <% end %>
      </div>
      </div>
</div>

app/views/products/index.html.erb
<!-- Slider Area -->
	<section class="hero-slider bordo_verifica">
		<!-- Single Slider -->
		<div class="single-slider">
			<div class="container">
				<div class="row no-gutters">
					<div class="col-lg-9 offset-lg-3 col-12">
						<div class="text-inner ">
							<div class="row reveal-">
								<div class="col-lg-7 col-12">
									<div class="hero-text">
										<h1>Ordina ciò di cui hai più bisgono</h1>
										<p>Un assistente nella tua zona accetterà l'ordine e ti consegnerà tutto presso la tua abitazione</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!--/ End Single Slider -->
	</section>
<!--/ End Slider Area -->





<!-- Start Small Banner  -->
	<section class="small-banner section bordo_verifica bg_celeste_chiaro">
		<div class="container-fluid">
			<div class="row">
				<!-- Single Banner  -->
				<div class="col-lg-4 col-md-6 col-12">
					<div class="single-banner art1 reveal- mt-4">	
						<div class="content">
							<h3>Prodotti freschi<br> Frutta, verdura, generi alimentari...</h3>
						</div>
					</div>
				</div>
				<!-- /End Single Banner  -->
				<!-- Single Banner  -->
				<div class="col-lg-4 col-md-6 col-12">
					<div class="single-banner art2 reveal- mt-4">
						<div class="content">
							<h3>Farmaci<br>I più importanti che non possono mancare</h3>
						</div>
					</div>
				</div>
				<!-- /End Single Banner  -->
				<!-- Single Banner  -->
				<div class="col-lg-4 col-12">
					<div class="single-banner tab-height art3 reveal- mt-4">
						
							


<input type="hidden" id="page" value="shop">
      <input type="hidden" id="current_lat" value="<%= current_user.lat%>">
      <input type="hidden" id="current_long" value="<%= current_user.long%>">
       <% User.where(:roles_mask => 2,:citta => current_user.citta ).each do |person| %>
                                <input type="hidden" class="others_lat" value="<%= person.lat%>">
                                <input type="hidden" class="others_long" value="<%= person.long%>">
                            <% end %>
<div class="bordo_verifica margin_map" id="map" style="border-radius: 15px;"></div>
						
					</div>
				</div>
				<!-- /End Single Banner  -->
			</div>
		</div>
	</section>
<!-- End Small Banner -->
<!-- Start Product Area -->
    <div class="product-area section bordo_verifica bg_celeste_chiaro">
    <%if can? :create, Product %>
    <%= link_to "Aggiungi Prodotto", new_product_path, :method => :get , :class=> 'btn btn-primary' %>
                      
    <%end%>
            <div class="container">
				<div class="row reveal">
					<div class="col-12 bordo_verifica">
						<div class="section-title allinea_testo_prodotti" style="text-align: center;">
							<h2>Tutti i prodotti</h2>
						</div>
					</div>
				</div>
				<div class="row reveal">
					<div class="col-12">
						<div class="product-info">
							<div class="nav-main">
								<!-- Tab Nav -->

								<ul class="nav nav-tabs" id="myTab" role="tablist">
                  <li class="nav-item"><a class="nav-link active" data-toggle="tab" href="#tutt" role="tab">Tutti</a></li>
									<li class="nav-item"><a class="nav-link" data-toggle="tab" href="#farm" role="tab">Farmacia</a></li>
									<li class="nav-item"><a class="nav-link" data-toggle="tab" href="#pul" role="tab">Pulizia</a></li>
									<li class="nav-item"><a class="nav-link" data-toggle="tab" href="#bag" role="tab">Bagno</a></li>
									<li class="nav-item"><a class="nav-link" data-toggle="tab" href="#alim" role="tab">Alimentari</a></li>
								</ul>

								
							</div>
							<div class="tab-content" id="myTabContent">

                <div class="tab-pane fade show active" id="tutt" role="tabpanel">
									<div class="tab-single">
										<div class="row" id="tutti">

                                        <% Product.all.each do |product| %>
                                            <div class="col-xl-3 col-lg-4 col-md-4 col-12">
                       <div class="single-product">
                          <div class="product-img">
                          <a>
                           <img style="height: 200px;" class="default-img" src="<%= product.imagePath%>" alt="#">
                           </a>
                           <div class="button-head">
                              <div class="product-action-2 tx_pd_1" style="text-align: center;">
                                <%if can? :update, Product %>
        <%= link_to "Modifica", edit_product_path(product) %>
    <%end%>
    <%if can? :destroy, Product %>
        <%= link_to "Elimina", product_path(product), :method => :delete %>
    <%end%>
    <%if can? :create, Cart %>
        <%= form_with url: carts_path, method: :post do |form| %>
            <input type="hidden" name="id" value="<%= product.id.to_s%>">
            <input type="submit" value="Aggiungi al carrello">
        <% end %>
        <% end %>
                             </div>
                           </div>
                         </div>
                          <div class="product-content">
                            <h3><%= product.title %></h3>
                         </div>
                         <p><%= product.description%></p>
                       </div>
                     </div>
                                        <% end %>

										</div>
									</div>
								</div>
								
								<div class="tab-pane fade" id="farm" role="tabpanel">
									<div class="tab-single">
										<div class="row" id="farmaci">

                                        <% Product.where(:category => 'Farmacia').each do |product| %>
                                            <div class="col-xl-3 col-lg-4 col-md-4 col-12">
                       <div class="single-product">
                          <div class="product-img">
                          <a>
                           <img style="height: 200px;" class="default-img" src="<%= product.imagePath%>" alt="#">
                           </a>
                           <div class="button-head">
                              <div class="product-action-2 tx_pd_1" style="text-align: center;">
                               <%if can? :update, Product %>
        <%= link_to "Modifica", edit_product_path(product) %>
    <%end%>
    <%if can? :destroy, Product %>
        <%= link_to "Elimina", product_path(product), :method => :delete %>
    <%end%>
    <%if can? :create, Cart %>
        <%= form_with url: carts_path, method: :post do |form| %>
            <input type="hidden" name="id" value="<%= product.id.to_s%>">
            <input type="submit" value="Aggiungi al carrello">
        <% end %>
        <% end %>
                             </div>
                           </div>
                         </div>
                          <div class="product-content">
                            <h3><%= product.title %></h3>
                         </div>
                         <p><%= product.description%></p>
                       </div>
                     </div>
                                        <% end %>
								      

										</div>
									</div>
								</div>

                <div class="tab-pane fade" id="pul" role="tabpanel">
									<div class="tab-single">
										<div class="row" id="pulizie">

                                        <% Product.where(:category => 'Pulizia').each do |product| %>
                                           <div class="col-xl-3 col-lg-4 col-md-4 col-12">
                       <div class="single-product">
                          <div class="product-img">
                          <a>
                           <img style="height: 200px;" class="default-img" src="<%= product.imagePath%>" alt="#">
                           </a>
                           <div class="button-head">
                              <div class="product-action-2 tx_pd_1" style="text-align: center;">
                               <%if can? :update, Product %>
        <%= link_to "Modifica", edit_product_path(product) %>
    <%end%>
    <%if can? :destroy, Product %>
        <%= link_to "Elimina", product_path(product), :method => :delete %>
    <%end%>
    <%if can? :create, Cart %>
        <%= form_with url: carts_path, method: :post do |form| %>
            <input type="hidden" name="id" value="<%= product.id.to_s%>">
            <input type="submit" value="Aggiungi al carrello">
        <% end %>
        <% end %>
                             </div>
                           </div>
                         </div>
                          <div class="product-content">
                            <h3><%= product.title %></h3>
                         </div>
                         <p><%= product.description%></p>
                       </div>
                     </div>
                                        <% end %>

										</div>
									</div>
								</div>

                <div class="tab-pane fade" id="bag" role="tabpanel">
									<div class="tab-single">
										<div class="row" id="bagni">

                                        <% Product.where(:category => 'Bagno').each do |product| %>
                                            <div class="col-xl-3 col-lg-4 col-md-4 col-12">
                       <div class="single-product">
                          <div class="product-img">
                          <a>
                           <img style="height: 200px;" class="default-img" src="<%= product.imagePath%>" alt="#">
                           </a>
                           <div class="button-head">
                              <div class="product-action-2 tx_pd_1" style="text-align: center;">
                               <%if can? :update, Product %>
        <%= link_to "Modifica", edit_product_path(product) %>
    <%end%>
    <%if can? :destroy, Product %>
        <%= link_to "Elimina", product_path(product), :method => :delete %>
    <%end%>
    <%if can? :create, Cart %>
        <%= form_with url: carts_path, method: :post do |form| %>
            <input type="hidden" name="id" value="<%= product.id.to_s%>">
            <input type="submit" value="Aggiungi al carrello">
        <% end %>
        <% end %>
                             </div>
                           </div>
                         </div>
                          <div class="product-content">
                            <h3><%= product.title %></h3>
                         </div>
                         <p><%= product.description%></p>
                       </div>
                     </div>
                                        <% end %>

										</div>
									</div>
								</div>

                <div class="tab-pane fade" id="alim" role="tabpanel">
									<div class="tab-single">
										<div class="row" id="alimenti">
                                        <% Product.where(:category => 'Alimentari').each do |product| %>
                                            <div class="col-xl-3 col-lg-4 col-md-4 col-12">
                       <div class="single-product">
                          <div class="product-img">
                          <a>
                           <img style="height: 200px;" class="default-img" src="<%= product.imagePath%>" alt="#">
                           </a>
                           <div class="button-head">
                              <div class="product-action-2 tx_pd_1" style="text-align: center;">
                               <%if can? :update, Product %>
        <%= link_to "Modifica", edit_product_path(product) %>
    <%end%>
    <%if can? :destroy, Product %>
        <%= link_to "Elimina", product_path(product), :method => :delete %>
    <%end%>
    <%if can? :create, Cart %>
        <%= form_with url: carts_path, method: :post do |form| %>
            <input type="hidden" name="id" value="<%= product.id.to_s%>">
            <input type="submit" value="Aggiungi al carrello">
        <% end %>
        <% end %>
                             </div>
                           </div>
                         </div>
                          <div class="product-content">
                            <h3><%= product.title %></h3>
                         </div>
                         <p><%= product.description%></p>
                       </div>
                     </div>
                                        <% end %>
                      

										</div>
									</div>
								</div>

							</div>

						</div>
					</div>
				</div>
      </div>
    </div>
<!-- End Product Area -->

app/views/products/new.html.erb
<div style="height: 80vh; margin-top:2cm;">
<div class="row mx-auto" style="margin-bottom: 0.5cm;">
    <div class="col-md-4 col-md-offset-4 mx-auto">
        <h1 class="text-center" style="font-size: 30px;">Crea Prodotto
        </h1>
      <%= form_with url: products_path ,class: "formABC" ,method: :post do |form| %>
        <%= render partial: "product_form", locals: {form: form, product: nil} %>
        
        <input type="submit" class="btn btn-success">

      <% end %>
      </div>
      </div>
</div>